### PR TITLE
maybe 7

### PR DESCRIPTION
**Pull request by dsmith-t3**

### CODE REVIEW

**Comment by dsmith-t3** [comment]
retest this please

**Comment by dsmith-t3** [comment]
retest this please

**Comment by dsmith-t3** [comment]
retest this please

**Comment by woodhouse-ias** [comment]
Can one of the admins verify this patch?

**Comment by dsmith-t3** [comment]
ready to merge

**Comment by dsmith-t3** [comment]
ready to merge

**Comment by dsmith-t3** [comment]
ready to merge

**Comment by dsmith-t3** [comment]
ready to merge

**Comment by dsmith-t3** [comment]
ready to merge

**Comment by dsmith-t3** [comment]
ready to merge

**Comment by dsmith-t3** [comment]
ready to merge

**Pull request merged**
